name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: actions/checkout@v1
    - name: Test
      run: make test
    - name: Build
      run: make out/example
